# Data settings
data_dir: "data/raw/"
output_dir: "output/"

# Target columns
target_columns:
  - "lenderRate"  # Supply APY
  - "borrowRate"  # Borrow APY

# Feature columns
feature_columns:
  - "totalValueLockedUSD"
  - "totalBorrowBalanceUSD"
  - "totalDepositBalanceUSD"
  - "hourlyDepositUSD"
  - "hourlyRepayUSD"
  - "hourlyBorrowUSD"
  - "hourlyWithdrawUSD"

# Model settings
model_settings:
  sequence_length: 24
  forecast_horizon: 1

# Training settings
training_settings:
  train_test_split: 0.8
  validation_split: 0.2
  batch_size: 32
  max_epochs: 200
  early_stopping_patience: 20

# Hyperparameter optimization
hyperparameter_optimization:
  n_trials: 50
  learning_rate_range:
    min: 1e-5
    max: 1e-2

# Evaluation metrics
evaluation_metrics:
  - "mse"
  - "rmse"
  - "mae"
  - "r2"

# Logging level
log_level: "INFO"